# Generated by Django 4.2.5 on 2023-09-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
