# Generated by Django 4.2.5 on 2023-09-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_range',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
